EmprestimosLivros/Models/EmprestimosModel.cs
using System.ComponentModel.DataAnnotations;

namespace EmprestimosLivros.Models
{
    public class EmprestimosModel 
        //Na model que vai referenciar a cada coluna no banco de dados
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Digite o nome do recebedor!")] 
        public string Recebedor { get; set; }

        [Required(ErrorMessage = "Digite o nome do Fornecedor!")]
        public string Fornecedor { get; set;}

        [Required(ErrorMessage = "Digite o nome do Livro!")]
        public string LivroEmprestado { get; set;}  
        public DateTime DataEmprestimo { get; set; } = DateTime.Now;

    }
}

EmprestimosLivros/Models/ErrorViewModel.cs
namespace EmprestimosLivros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmprestimosLivros/Controllers/EmprestimosController.cs
using EmprestimosLivros.Data;
using EmprestimosLivros.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmprestimosLivros.Controllers
{
    public class EmprestimosController : Controller
    {
        readonly private ApplicationDbContext _db; //depois do ctor criar esta referencia aqui, e em seguida cita dentro do construtor;
        public EmprestimosController(ApplicationDbContext db) // depois de criar a view e conectar com a model, criar este onstrutor
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var emprestimos = _db.EmprestarLivros.ToList(); //Aqui entra no banco e busca a tabela completa;

            return View(emprestimos);
        }
        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();  
        }
        [HttpPost]
        public IActionResult Cadastrar(EmprestimosModel emprestimos) //depois de indicar a controller no form, coloca os parametros;
        {
            //cria a condição
            if(ModelState.IsValid)//se o estado da model é válido
            {
                _db.EmprestarLivros.Add(emprestimos); //buscou no banco a tabela emprestimos
                _db.SaveChanges();


                return RedirectToAction("Index");

            }
            return View();
        }
        // EDITAR------------------------------
        [HttpGet]
        public IActionResult Editar(int? Id)
        {
            if(Id == null || Id == 0)
            {
                return NotFound();
            }
            EmprestimosModel emprestimo = _db.EmprestarLivros.FirstOrDefault(x => x.Id == Id);

            if (emprestimo == null)
            {
                return NotFound();
            }
            return View(emprestimo);
            //até aqui é para retornar as informaçoes da tela editar
        }
        [HttpPost]
        public IActionResult Editar(EmprestimosModel emprestimos)
        {
            if(ModelState.IsValid)
            {
                _db.EmprestarLivros.Update(emprestimos);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(emprestimos);        
        
        }

        //EXCLUIR-------------------------------------------------------------------------

        [HttpGet]
        public IActionResult Excluir(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }
            EmprestimosModel emprestimo = _db.EmprestarLivros.FirstOrDefault(x => x.Id == Id); // X É A COLUNA

            if (emprestimo == null)
            {
                return NotFound();
            }
            return View(emprestimo);
        }
        [HttpPost]
        public IActionResult Excluir(EmprestimosModel emprestimos)
        { 
            if(emprestimos == null)
            {
                return NotFound();
            }
            _db.EmprestarLivros.Remove(emprestimos);
            _db.SaveChanges();
            return RedirectToAction("Index");
            
        }
    }
    
    
}

EmprestimosLivros/Controllers/HomeController.cs
using EmprestimosLivros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmprestimosLivros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmprestimosLivros/Views/Emprestimos/Cadastrar.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "cadastrar";
}

<div class="container">
    <div>
        <h1>Cadastro de Empréstimo</h1>
    </div>
    
    @*Para Adicionar, o código pega os dados no banco e salva no banco; coloca METHOD de POST no form,
    entao adiciona o controller e o metodo que quer usar; ex <form asp-controller="Emprestimos" asp-action="Cadastrar">
    *@

    <form asp-controller="Emprestimos" asp-action="Cadastrar"> 
        <div class="mb-3">
            <label for="Recebedor" class="form-label">Recebedor:</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="recebedor" placeholder="Quem está recebendo o livro?">
            <span asp-validation-for="Recebedor" class="text-danger"></span>
        </div>


        <div class="mb-3">
            <label for="Fornecedor" class="form-label">Fornecedor</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o livro?">
            <span asp-validation-for="Fornecedor" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label for="livro" class="form-label">Livro</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o livro que está sendo emprestado?">
            <span asp-validation-for="LivroEmprestado" class="text-danger"></span>
        </div>


        
        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-primary">Adicionar</button>
            <a class="btn btn-primary " asp-controller="Emprestimos" asp-action="Index"> Voltar </a>
        </div>
    </form>
</div>

EmprestimosLivros/Views/Emprestimos/Editar.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Editar";
}

<div class="container">
    <div>
        <h1>Edição de emprestimo</h1>
    </div>

    @*Para Adicionar, o código pega os dados no banco e salva no banco; coloca METHOD de POST no form,
    entao adiciona o controller e o metodo que quer usar; ex <form asp-controller="Emprestimos" asp-action="Cadastrar">
    *@

    <form asp-controller="Emprestimos" asp-action="Editar">
        <input type="hiden" asp-for="Id" />

        <div class="mb-3">
            <label for="Recebedor" class="form-label">Recebedor:</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="recebedor" placeholder="Quem está recebendo o livro?">
            <span asp-validation-for="Recebedor" class="text-danger"></span>
        </div>


        <div class="mb-3">
            <label for="Fornecedor" class="form-label">Fornecedor</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o livro?">
            <span asp-validation-for="Fornecedor" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label for="livro" class="form-label">Livro</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o livro que está sendo emprestado?">
            <span asp-validation-for="LivroEmprestado" class="text-danger"></span>
        </div>



        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-sucess">Editar</button>
            <a class="btn btn-primary m-40 form-control-coloralert" asp-controller="Emprestimos" asp-action="Index"> Voltar </a>

        </div>
    </form>
</div>

EmprestimosLivros/Views/Emprestimos/Excluir.cshtml
@model EmprestimosModel
@{
    ViewData["title"] = "Excluir";
}

<div class="container">
    <div>
        <h1> Tem certeza que deseja Excluir?</h1>
    </div>

    @*Para Adicionar, o código pega os dados no banco e salva no banco; coloca METHOD de POST no form,
    entao adiciona o controller e o metodo que quer usar; ex <form asp-controller="Emprestimos" asp-action="Cadastrar">
    *@

    <form asp-controller="Emprestimos" asp-action="Excluir">
        <input type="hidden" asp-for="Id" />

        <div class="mb-3">
            <label for="Recebedor" class="form-label">Recebedor:</label>
            <input type="text" class="form-control" asp-for="Recebedor" id="recebedor" placeholder="Quem está recebendo o livro?" disabled>
            <span asp-validation-for="Recebedor" class="text-danger"></span>
        </div>


        <div class="mb-3">
            <label for="Fornecedor" class="form-label">Fornecedor</label>
            <input type="text" class="form-control" asp-for="Fornecedor" id="Fornecedor" placeholder="Quem está emprestando o livro?" disabled>
            <span asp-validation-for="Fornecedor" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label for="livro" class="form-label">Livro</label>
            <input type="text" class="form-control" asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o livro que está sendo emprestado?" disabled>
            <span asp-validation-for="LivroEmprestado" class="text-danger"></span>
        </div>



        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger">Excluir</button>
            <a class="btn btn-primary" asp-controller="Emprestimos" asp-action="Index"> Voltar </a>

        </div>
    </form>
</div>

EmprestimosLivros/Views/Emprestimos/Index.cshtml
@model IEnumerable<EmprestimosModel> //Aqui faz a rferencia da model do projeto. E colocar  dentro da estrutura Ienumerable

<div class="container">
    <div class=" d-flex justify-content-between align-items-center mb-5">
        <h1>Emprestimos</h1>
        <a class="btn btn-success" asp-controller="Emprestimos" asp-action="Cadastrar"><i class="bi bi-file-earmark-plus"> Cadastrar Novo empréstimo </i></a>
    </div>
</div>

<table  class="table table-bordered border-primary table-hover">
    <thead>
        <tr>          
            <th scope="col" class="text-center"><strong>Recebedor</strong></th>
            <th scope="col" class="text-center"><strong>Fornecedor</strong></th>
            <th scope="col" class="text-center"><strong>Livro</strong></th>
            <th scope="col" class="text-center"><strong>Data</strong></th>
            <th class="text-center"><strong>Ações</strong></th>
           
        </tr>
    </thead>
    <tbody>
        @if(Model != null)
        {
            @foreach (var emprestimo in Model)
            {
                <tr>

                    <td class="text-center">@emprestimo.Recebedor</td>
                    <td class="text-center">@emprestimo.Fornecedor</td>
                    <td class="text-center">@emprestimo.LivroEmprestado</td>
                    <td class="text-center">@emprestimo.DataEmprestimo</td>
                    <td class="text-center">
                        <a class="btn btn-warning mx-2" asp-controller="Emprestimos" asp-action="Editar" asp-route-id="@emprestimo.Id"><i class="bi bi-pencil-fill"> Editar</i></a>
                        <a class="btn btn-danger mx-2" asp-controller="Emprestimos" asp-action="Excluir" asp-route-id="@emprestimo.Id"> <i class="bi bi-trash-fill"> Excluir</i> </a>
                    </td>
                    
                </tr>
            }
          
            
        }
        
      
    </tbody>
</table>

EmprestimosLivros/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Início";
}

<div class="text-center">
    <h1 class="display-4">Empréstimo de Livro Online</h1>
    <p>Compartilhe conhecimentos</p>
    <div>
        <img  src="/img/coelho.png"/>
    </div>
   </div>

EmprestimosLivros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmprestimosLivros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Journal.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmprestimosLivros.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    
   
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">MyBookOnline</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"> <i class="bi bi-house"> Home </i> </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Emprestimos" asp-action="Index"><i class="bi bi-book"> Emprestar </i> </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" bg-primary>
        <div class="container">
            &copy; 2024 - EmprestimosLivros - <a asp-area="" asp-controller="Home" asp-action="Privacy">Empréstimo de Livros</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>